source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "activerecord"
gem "slim"
gem "mysql2"
gem "puma"
gem "rake"
gem "sinatra-activerecord"
gem "bcrypt"
gem "sinatra-flash"
gem "i18n"
gem "unirest"
gem "octokit"
gem "monacoin_client"
